apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-synbench
  labels:
    app: test-synbench
spec:
  replicas: 2
  selector:
    matchLabels:
      app: synbench01pod
  template:
    metadata: 
      labels:
        app: synbench01pod
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
      containers:
      - name: synbench01pod
        command: ["./applications.iot.workloads.synbench"]
        args: ["/share/default.txt"]
        image: yockgen/synbench:1.0
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME","NET_RAW"]
          runAsUser: 0
          privileged: true
        env:
          - name: XDG_RUNTIME_DIR 
            value: "/tmp"
          - name: DISPLAY
            value: ":0"
        volumeMounts:
          - name: dev-gpu
            mountPath: /dev/dri/card0
        volumeMounts:
          - name: gpu-config
            mountPath: /share/default.txt
        #volumeMounts:
        #  - name: xauth
        #    mountPath: /root/.Xauthority
      volumes:
        - name: dev-gpu
          hostPath:
            path: /dev/dri/card1
        - name: gpu-config
          hostPath:
            path: /data/synbench/default.txt
        #- name: xauth
        #  hostPath:
        #    path: /home/yockgenm/.Xauthority
 
