apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.id }}
  labels:
    app: {{ .Values.id }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.idPod }}
  template:
    metadata:
      labels:
        app: {{ .Values.idPod }}
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
      containers:
      - name: {{ .Values.idPod }}
        command: ["./applications.iot.workloads.synbench"]
        args: ["/share/default.txt"]
        image: yockgen/synbench:1.0
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME","NET_RAW"]
          runAsUser: 0
          privileged: true
        env:
          - name: XDG_RUNTIME_DIR
            value: "/tmp"
          - name: DISPLAY
            value: ":0"
        volumeMounts:
          - name: xauth
            mountPath: /root/.Xauthority
        volumeMounts:
          - name: dev-gpu
            mountPath: /dev/dri/card0
        volumeMounts:
          - name: gpu-config
            mountPath: /share/default.txt
      volumes:
        - name: dev-gpu
          hostPath:
            path: {{ .Values.gpu }}
        - name: gpu-config
          hostPath:
            path: /data/synbench/default.txt
        - name: xauth
          hostPath: 
            path: /home/yockgenm/.Xauthority

